imports_granularity = "Crate" # Nightly required
group_imports = "StdExternalCrate" # Nightly required
newline_style = "Unix"
normalize_comments = true # Nightly required
style_edition = "2021"
unstable_features = true
use_field_init_shorthand = true
