[editor]
idle-timeout = 200

[bindings.normal]
":" = "enter_command_mode"
i = "enter_insert_mode"
h = "move_cursor_prev"
j = "move_line_next"
k = "move_line_prev"
l = "move_cursor_next"

[bindings.insert]
j = { j = "enter_normal_mode" }

[bindings.command]
"<esc>" = "cancel"
q = "quit"