[package]
name = "rustle_core"
version = "0.1.0"
edition = "2024"

[dependencies]
ropey = "1.6.1"
rustle_state = { version = "0.1.0", path = "../rustle_state" }
serde = { version = "1.0.228", features = ["derive"] }
taffy = "0.9.1"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["macros", "rt"] }
tokio-stream = "0.1.17"
toml = "0.9.8"
unicode-display-width = "0.3.0"
unicode-segmentation = "1.12.0"
