name: Build WebUI
on:
  workflow_run:
    workflows: ["Test All"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd rustle_webui
      - run: npm install # is this actually needed?
      - run: npm run build
      - run: ls
