name: Build WebUI
on:
  workflow_run:
    workflows: ["Test All"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rustle_webui
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install NPM Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Push to website
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'rustle_webui/dist'
          destination-github-username: 'nickbryan'
          destination-repository-name: 'nickbryan.co.uk'
          target-directory: 'static/rustle'
